### ISSUE TITLE
couldn't install from npm

### ISSUE THREAD

**Issue by deanm0000** [holdenmatt/duckdb-wasm-kit#1]
doing `npm install duckdb-wasm-kit` resulted in:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@holdenmatt%2fts-utils - Not found
npm ERR! 404 
npm ERR! 404  '@holdenmatt/ts-utils@^0.1.11' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by holdenmatt** [comment]
Thanks for trying it and letting me know.

This should be fixed now, can you try again?

**Comment by deanm0000** [comment]
good to go now. Thanks.

**Comment by holdenmatt** [comment]
Great, thanks. Let me know if you run into any other issues!
