### ISSUE TITLE
Eventually create a dev version for the latest duckdb-wasm dev release

### ISSUE THREAD

**Issue by tobilg** [holdenmatt/duckdb-wasm-kit#10]
It'd be really great to have a (dev) version that supports the dynamic loading of extension with DuckDB-WASM.

**Comment by holdenmatt** [comment]
I tried upgrading to the latest duckdb-wasm version on npm, but it seems JSDelivr hosting is broken because the package is now too big:
https://github.com/duckdb/duckdb-wasm/issues/1561

I don't think it makes sense for me to host the wasm files, or make it a requirement for users of this library to host them. So I'll need to wait until the JsDelivr issue is fixed before upgrading (hopefully soon).

**Comment by tobilg** [comment]
Thanks for the feedback, I agree. There seems to be some progress now: https://github.com/duckdb/duckdb-wasm/pull/1589 

Thus, https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.28.1-dev89.0 was release a few hours ago which is 185MB unpacked now, compared to 1.63GB in the last version...

**Comment by holdenmatt** [comment]
Nice.

It looks like the JsDelivr links have a limit of 150MB: https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev89.0/dist/duckdb-browser-eh.worker.js

I'll try to keep an eye on progress (or feel free to ping here if it gets solved, and I'll do the upgrade). Thanks!

**Comment by tobilg** [comment]
It's now down to 138MB with https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.28.1-dev91.0

**Comment by carlopi** [comment]
@holdenmatt / @tobilg: this has indeed solved with the latest build, sorry for the inconvenience, I will shortly add a CI check that sizes have to be compatible with jsdelivr limits so to avoid regressions

**Comment by holdenmatt** [comment]
Ah great, thanks @carlopi!

Confirmed the JsDelivr links are working for me on the latest version. Will upgrade versions later today.

**Comment by tobilg** [comment]
Looking forward to the new release, thanks!

**Comment by holdenmatt** [comment]
Ok, this has now been upgraded to the latest duckdb-wasm version.
I haven't seen any issues in my testing but let me know if anything isn't working for you :)

<img width="828" alt="image" src="https://github.com/holdenmatt/duckdb-wasm-kit/assets/764380/ad067fc4-59e2-4ec0-b700-510cbd611494">

**Comment by tobilg** [comment]
Thank you very much @holdenmatt!
